version: 2.1

jobs:
  validate:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout
      - run:
          name: Install HTMLHint, Stylelint, ESLint
          command: |
            npm install -g htmlhint stylelint stylelint-config-standard eslint
      - run:
          name: Lint HTML
          command: |
            htmlhint index.html
      - run:
          name: Lint CSS
          command: |
            echo '{ "extends": "stylelint-config-standard" }' > .stylelintrc.json
            stylelint "**/*.css"
      - run:
          name: Lint JS
          command: |
            eslint --init --yes
            eslint script.js

workflows:
  version: 2
  test-site:
    jobs:
      - validate
